
spring:
  datasource:
    name: traveldatabase  #数据库名
    url: jdbc:mysql://124.70.209.207:3306/traveldatabase?characterEncoding=utf8&useUnicode=true #url
    username: root  #用户名
    password: Qaz225225225  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.dxhdemo.bean #配置实体类

hikari:
  minimum-idle: 3  # 最小空闲连接数量
  maximum-pool-size: 5  # 连接池最大连接数，默认是10
  max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
  connection-test-query: SELECT 1
